 -
  name: Export Environment Variable and Invoke java class
  hosts: App_Server_{{ currentEnvironment }}
 
  tasks:
         
     -
       name: include variables    
       include_vars:
          file: "vars/{{ currentEnvironment }}.yml"
          name: env_vars


     -
       name: change Dir and run Java
       shell:  java HelloWorld > output4.txt  chdir=/home/osboxes
       environment: "{{env_vars}}"
        
